version: '3.4'
services:
  psql:
    image: postgres:13-alpine
    restart: always
    container_name: project-psql
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: user1
        POSTGRES_PASSWORD: dm
        POSTGRES_DB: user1
    ports:
      - 5432:5432


