version: '3.4'
services:
  psql:
    image: postgres
    restart: always
    container_name: my-project-psql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: my-project
    ports:
      - 5432:5432


